<a href="https://colab.research.google.com/github/mhrznamrit/dsml_batch_12/blob/main/Day30_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Age": [25,30,35],
    "City": ['Kathmandu', 'Pokhara', 'Butwal']
}

In [ ]:
df = pd.DataFrame(data, index=['Ram', 'Shyam', 'Hari'])
df

       Age       City
Ram     25  Kathmandu
Shyam   30    Pokhara
Hari    35     Butwal

In [ ]:
df.loc['Shyam']

Age          30
City    Pokhara
Name: Shyam, dtype: object

In [ ]:
df['Age']

Ram      25
Shyam    30
Hari     35
Name: Age, dtype: int64

In [ ]:
df.iloc[1]

Age          30
City    Pokhara
Name: Shyam, dtype: object

In [ ]:
df.loc['Ram':'Shyam']

       Age       City
Ram     25  Kathmandu
Shyam   30    Pokhara

In [ ]:
df.iloc[0:3:2]

      Age       City
Ram    25  Kathmandu
Hari   35     Butwal

In [ ]:
df.loc['Ram','City']

'Kathmandu'

In [ ]:
df.iloc[0,1]

'Kathmandu'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
titanic_df = pd.read_csv('/content/drive/MyDrive/DSML12/titanic-data.csv')

In [ ]:
titanic_df.shape

(891, 12)

In [ ]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [ ]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
titanic_df[["Age","Fare"]].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [ ]:
titanic_df[["Age","Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [ ]:
titanic_df.value_counts("Survived")

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
titanic_df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Sex", "Survived"], ascending=True)

Sex     Survived
female  0            81
male    1           109
female  1           233
male    0           468
Name: count, dtype: int64

In [ ]:
titanic_df.value_counts(["Sex", "Survived"], normalize=True, ascending=True)

Sex     Survived
female  0           0.090909
male    1           0.122334
female  1           0.261504
male    0           0.525253
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Sex']=='female'].value_counts("Survived", ascending=True, normalize=True)

Survived
0    0.257962
1    0.742038
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Sex']=='male'].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.188908
0    0.811092
Name: proportion, dtype: float64

In [ ]:
titanic_df.value_counts(["Pclass", "Survived"], ascending=True)

Pclass  Survived
1       0            80
2       1            87
        0            97
3       1           119
1       1           136
3       0           372
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df['Pclass'] == 1].value_counts("Survived", ascending=True, normalize=True)

Survived
0    0.37037
1    0.62963
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Pclass'] == 2].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.472826
0    0.527174
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Pclass'] == 3].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.242363
0    0.757637
Name: proportion, dtype: float64

In [ ]:
# 1. Define bin boundaries and corresponding labels
bins = [0, 12, 19, 59, 100]
labels = ["Child", "Teenager", "Adult", "Senior"]

# 2. Create the new column
titanic_df["AgeGroup"] = pd.cut(
    titanic_df["Age"], bins=bins, labels=labels, right=True
)

# 3. Check value counts with Survived
titanic_df.value_counts(["AgeGroup", "Survived"], ascending=True)

AgeGroup  Survived
Senior    1             7
          0            19
Child     0            29
Teenager  1            39
Child     1            40
Teenager  0            56
Adult     1           204
          0           320
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df['AgeGroup'] == "Child"].value_counts("Survived", ascending=True, normalize=True)

Survived
0    0.42029
1    0.57971
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['AgeGroup'] == "Teenager"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.410526
0    0.589474
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['AgeGroup'] == "Adult"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.389313
0    0.610687
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['AgeGroup'] == "Senior"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.269231
0    0.730769
Name: proportion, dtype: float64

In [ ]:
titanic_df["FareClass"] = pd.cut(
    titanic_df["Fare"], bins=[0,150,300,450,600], labels=['Low', 'Medium', 'High', 'Very High'], right=True
)
titanic_df.value_counts(["FareClass", "Survived"], ascending=True)

FareClass  Survived
Very High  1             3
Medium     0             9
           1            17
Low        1           321
           0           526
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df['FareClass'] == "Low"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.378985
0    0.621015
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['FareClass'] == "Medium"].value_counts("Survived", ascending=True, normalize=True)

Survived
0    0.346154
1    0.653846
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['FareClass'] == "High"].value_counts("Survived", ascending=True, normalize=True)

Series([], Name: proportion, dtype: float64)

In [ ]:
titanic_df[titanic_df['FareClass'] == "Very High"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    1.0
Name: proportion, dtype: float64

In [ ]:
titanic_df.value_counts(["Embarked"], ascending=True)

Embarked
Q            77
C           168
S           644
Name: count, dtype: int64

In [ ]:
titanic_df[titanic_df['Embarked'] == "Q"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.38961
0    0.61039
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Embarked'] == "C"].value_counts("Survived", ascending=True, normalize=True)

Survived
0    0.446429
1    0.553571
Name: proportion, dtype: float64

In [ ]:
titanic_df[titanic_df['Embarked'] == "S"].value_counts("Survived", ascending=True, normalize=True)

Survived
1    0.336957
0    0.663043
Name: proportion, dtype: float64

In [ ]:
print("Average Fare: ",titanic_df["Fare"].mean())

Average Fare:  32.204207968574636